const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require(process.env.IDLE_JSDOM_PATH || 'jsdom');
const html = fs.readFileSync('dist/index.html','utf8');
const bundle = fs.readFileSync('dist/app.bundle.js','utf8');
const dom = new JSDOM(html,{url:'https://example.github.io/idle/',runScripts:'outside-only'});
const w=dom.window,d=w.document,errors=[],downloads=[];
w.addEventListener('error',e=>errors.push(e.error || e.message));
w.scrollTo=()=>{};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
w.URL.createObjectURL=value=>{downloads.push(value);return 'blob:idle-export';};w.URL.revokeObjectURL=()=>{};
w.HTMLAnchorElement.prototype.click=function(){assert.ok(this.download.endsWith('.json'));};
d.execCommand=()=>true;
const address='11111111111111111111111111111111', other='22222222222222222222222222222222';
let change, connections=0, disconnects=0;
const account={address,chains:['solana:mainnet']};
const wallet={name:'Solflare',chains:['solana:mainnet'],features:{'standard:connect':{connect:async()=>{connections++;return {accounts:[account]};}},'standard:disconnect':{disconnect:async()=>{disconnects++;}},'standard:events':{on:(event,fn)=>{change=fn;return ()=>change=null;}}}};
w.addEventListener('wallet-standard:app-ready',e=>e.detail.register(wallet));
const click=selector=>{const el=d.querySelector(selector);assert.ok(el,selector);el.click();};
const input=(selector,value,type='input')=>{const el=d.querySelector(selector);assert.ok(el,selector);el.value=value;el.dispatchEvent(new w.Event(type,{bubbles:true}));};
const submit=selector=>d.querySelector(selector).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
  w.eval(bundle);
  assert.match(d.querySelector('h1').textContent,/Plan your tasks.*AI agents/);
  assert.doesNotMatch(d.body.textContent,/demo|simulat|fixture/i);
  assert.ok(d.body.classList.contains('landing-mode'));
  click('[data-landing-example="1"]');
  assert.equal(d.querySelector('[data-landing-example="1"]').getAttribute('aria-pressed'),'true');
  assert.match(d.querySelector('.landing-product-preview').textContent,/Review a Solana integration/);
  const preferred=d.querySelector('#landing-agent option[value]:not([value=""])');
  assert.ok(preferred);
  input('#landing-agent',preferred.value,'change');
  assert.match(d.querySelector('.landing-product-preview').textContent,new RegExp(preferred.textContent.split(' · ')[0]));
  click('[data-use-landing-plan]');
  assert.equal(d.querySelector('#task-title').value,'Review a Solana integration');
  assert.equal(d.querySelector('#preferred-agent').value,preferred.value);
  assert.ok(!d.body.classList.contains('landing-mode'));
  click('[data-nav="introduction"]');
  click('[data-start-example="2"]');
  assert.equal(d.querySelector('#task-title').value,'Summarize a document');
  assert.equal(d.querySelector('#capability').value,'Summarization');
  click('[data-nav="introduction"]');

  click('[data-nav="overview"]');assert.equal(d.querySelectorAll('.task-card').length,3);assert.match(d.querySelector('.feed').textContent,/Starter task plans/);
  click('[data-nav="network"]');assert.equal(d.querySelectorAll('.agent-card').length,3);
  click('[data-add-agent]');input('#agent-name','Research endpoint');input('#agent-endpoint','https://example.org/tasks');d.querySelector('[name="caps"]').checked=true;submit('#agent-form');
  assert.equal(d.querySelectorAll('.agent-card').length,4);input('#agent-search','Research endpoint');click('[data-favorite]');assert.equal(d.querySelector('[data-favorite]').getAttribute('aria-pressed'),'true');
  click('[data-plan-agent]');input('#task-title','<img src=x onerror=alert(1)>');input('#instruction','Review Solana architecture.');
  assert.equal(d.querySelector('#plan-preview img'),null);submit('#task-form');assert.match(d.querySelector('.spec-output').textContent,/Review Solana architecture/);assert.match(d.querySelector('.spec-output').textContent,/https:\/\/example.org\/tasks/);
  click('[data-export]');assert.equal(downloads.length,1);click('#close-modal');click('[data-nav="activity"]');assert.equal(d.querySelectorAll('.task-card').length,4);
  input('#task-search','nonexistent');assert.equal(d.querySelectorAll('.task-card').length,0);input('#task-search','Review Solana architecture');assert.equal(d.querySelectorAll('.task-card').length,1);
  click('[data-reuse]');assert.equal(d.querySelector('#instruction').value,'Review Solana architecture.');
  click('#connect-top');assert.match(d.querySelector('.wallet-option').textContent,/Solflare/);click('[data-wallet]');await tick();assert.equal(connections,1);assert.match(d.querySelector('#connect-top').textContent,/Solflare/);
  click('[data-nav="activity"]');assert.equal(d.querySelectorAll('.task-card').length,3);
  click('[data-nav="route"]');click('[data-template="0"]');submit('#task-form');click('#close-modal');
  assert.equal(JSON.parse(w.localStorage.getItem('idle-workspace-v1')).profiles[address].tasks.length,4);
  change({accounts:[{address:other,chains:['solana:mainnet']}]});click('[data-nav="activity"]');assert.equal(d.querySelectorAll('.task-card').length,3);
  click('#connect-top');click('#disconnect-wallet');await tick();assert.equal(disconnects,1);assert.equal(d.querySelectorAll('.task-card').length,4);
  click('[data-nav="network"]');input('#agent-search','Research endpoint');click('[data-remove-agent]');click('[data-confirm-remove]');assert.equal(d.querySelectorAll('.agent-card').length,0);
  click('[data-nav="activity"]');click('[data-task]');assert.match(d.querySelector('.spec-output').textContent,/example.org/);click('#close-modal');
  for(const section of ['introduction','overview','network','route','activity','docs']){click(`[data-nav="${section}"]`);assert.doesNotMatch(d.querySelector('#app').textContent,/demo|simulat|fixture/i);}
  assert.equal(errors.length,0,errors.map(String).join('\n'));
  assert.equal(d.querySelectorAll('[src^="/"]').length,0);
  console.log('Bundled DOM audit passed: all views, safe preview, directory/favorites, planning, search/reuse/export, wallet connection/account change/disconnect, profile isolation, preserved snapshots, repository-subpath assets.');
  dom.window.close();
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
